### PR TITLE
Add support for RDF4J. Fixes #44

### LINKED ISSUE #44: Add integration with RDF4J
Eclipse RDF4J is about to release its first official version. It would be useful to add support for it in a similar way to the other integrations.

### PR DESCRIPTION
**Pull request by ansell**
Support for RDF4J as an integration module. Failing tests are also failing on the master branch.

### CODE REVIEW

**Comment by ansell** [comment]
I am not familiar with the RDFa compliance suite, but it may be possible that the test failures are new tests that are not yet supported by Semargl as they are occuring on the master branch also.

**Comment by ansell** [comment]
@levkhomich Do you have time to review this PR?

**Comment by levkhomich** [comment]
Sorry Peter, will try to find a time to review it by the end of this week.

**Comment by levkhomich** [comment]
Thank you for the contribution. Sorry it took so long.

**Comment by levkhomich** [comment]
Currently, I do not have much time to maintain the project, yet still I plan to fix existing issues with tests at leas. I gave you committer access in case you want to improve something.

**Comment by ansell** [comment]
Thanks for committing this. The ever changing nature of the testsuite will be an ongoing issue I think, but it is useful for interoperability to have the testsuite updated regularly to clarify things that are missed by it. Hopefully it stabilises at some point.

I don't foresee me committing to the core, but I will try to maintain the Sesame/RDF4J modules, as they are reused by a few projects that I in turn use (as you can see by the referenced issues above).

**Comment by ansell** [comment]
I don't mind doing release management if you don't have time for that. If you don't mind me doing that, could you comment on the relevant OSSRH Jira issue at Sonatype asking them to add push permissions to "org.semarglproject" for my Sonatype username, "p_ansell". It looks like it may be https://issues.sonatype.org/browse/OSSRH-9123 but the reference there is to com.github.levkhomich which isn't right.

**Pull request merged**
